### PR TITLE
bytes is a lot more efficient than chars.

### PR DESCRIPTION
**Pull request by gilescope**
I was recently improving to_digit in the std lib and came across this code and though we can do the same here. Unicode is complicated and here it isn't relevant.

### CODE REVIEW

**Comment by gilescope** [comment]
Forgot - wrapping_sub is key.

**Comment by abizjak** [comment]
When you say "a lot more efficient", what are we talking about?

This code is not used in any performance sensitive context, so clarity trumps slight efficiency differences.

To me it is clearer to talk about `char`s than bytes, the latter requiring us to deal with the details of encoding.

**Comment by limemloh** [comment]
Thank you for spending time on this, but I will close this MR, because I think correctness and readability is more importing for this part of our code base, than the performance gain.

**Comment by gilescope** [comment]
Sure - if it's not heavily used then that makes sense.

**Pull request closed without merging**
